# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('image_url', models.TextField()),
                ('fbid', models.TextField()),
                ('page_url', models.TextField()),
                ('recipe_text', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
