# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('fbid', models.TextField()),
                ('image_url', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='host_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_recipes.Facebook_Page'),
        ),
    ]
