# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_recipes', '0002_auto_20160906_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='host_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page', to='facebook_recipes.Facebook_Page'),
        ),
    ]
