# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_recipes', '0003_auto_20160906_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='host_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='host_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_recipes.Facebook_Page'),
        ),
    ]
