# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_recipes', '0004_auto_20160906_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
