# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_recipes', '0005_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created_ms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
